### ISSUE TITLE
Error in dmDSdata(counts = counts, samples = coldata) : 

### ISSUE THREAD

**Issue by cerdelyan** [nanoporetech/pipeline-transcriptome-de#1]
Hi Botond,

I'm having an issue when I try analyzing some data.

With the .gff3:
```
Activating conda environment: /home/user/pipeline-transcriptome-de/Workspaces/mosquito/.snakemake/conda/81c03226
Loading counts, conditions and parameters.
Loading annotation database.
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .extract_exons_from_GRanges(exon_IDX, gr, ID, Name, Parent, feature = "exon",  :
  The following orphan exon were dropped (showing only the 6 first):
  seqid  start    end strand   ID        Parent             Name
1     1  28171  28393      - <NA> AAEL020532-RA AAEL020532-RA-E2
2     1  28468  28857      - <NA> AAEL020532-RA AAEL020532-RA-E1
3     1  29507  29645      - <NA> AAEL027741-RA AAEL027741-RA-E2
4     1  29726  30127      - <NA> AAEL027741-RA AAEL027741-RA-E1
5     1 129789 129946      + <NA> AAEL021681-RA AAEL021681-RA-E1
6     1 142976 143057      + <NA> AAEL021681-RA AAEL021681-RA-E2
'select()' returned 1:many mapping between keys and columns
Filtering counts using DRIMSeq.
Error in dmDSdata(counts = counts, samples = coldata) : 
  all(samples$sample_id %in% colnames(counts)) is not TRUE
Calls: dmDSdata -> stopifnot
Execution halted
[Mon Feb 11 10:56:24 2019]
Error in rule de_analysis:
    jobid: 16
    output: de_analysis/results_dge.tsv, de_analysis/results_dge.pdf, de_analysis/results_dtu_gene.tsv, de_analysis/results_dtu_transcript.tsv, de_analysis/results_dtu_stageR.tsv, merged/all_counts_filtered.tsv, merged/all_gene_counts.tsv
    conda-env: /home/user/pipeline-transcriptome-de/Workspaces/mosquito/.snakemake/conda/81c03226

RuleException:
CalledProcessError in line 128 of /home/user/pipeline-transcriptome-de/Snakefile:
Command 'source activate /home/user/pipeline-transcriptome-de/Workspaces/mosquito/.snakemake/conda/81c03226; set -euo pipefail;  
    /home/user/pipeline-transcriptome-de/scripts/de_analysis.R ' returned non-zero exit status 1.
  File "/home/user/pipeline-transcriptome-de/Snakefile", line 128, in __rule_de_analysis
  File "/home/user/miniconda3/envs/pipetrans/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/user/pipeline-transcriptome-de/.snakemake/log/2019-02-11T102246.103956.snakemake.log 
```

With the .gtf:
```
Loading counts, conditions and parameters.
Loading annotation database.
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
Filtering counts using DRIMSeq.
Error in dmDSdata(counts = counts, samples = coldata) : 
  all(samples$sample_id %in% colnames(counts)) is not TRUE
Calls: dmDSdata -> stopifnot
Execution halted
[Mon Feb 11 11:20:36 2019]
Error in rule de_analysis:
    jobid: 16
    output: de_analysis/results_dge.tsv, de_analysis/results_dge.pdf, de_analysis/results_dtu_gene.tsv, de_analysis/results_dtu_transcript.tsv, de_analysis/results_dtu_stageR.tsv, merged/all_counts_filtered.tsv, merged/all_gene_counts.tsv
    conda-env: /home/user/pipeline-transcriptome-de/Workspaces/mosquito/.snakemake/conda/81c03226

RuleException:
CalledProcessError in line 128 of /home/user/pipeline-transcriptome-de/Snakefile:
Command 'source activate /home/user/pipeline-transcriptome-de/Workspaces/mosquito/.snakemake/conda/81c03226; set -euo pipefail;  
    /home/user/pipeline-transcriptome-de/scripts/de_analysis.R ' returned non-zero exit status 1.
  File "/home/user/pipeline-transcriptome-de/Snakefile", line 128, in __rule_de_analysis
  File "/home/user/miniconda3/envs/pipetrans/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/user/pipeline-transcriptome-de/.snakemake/log/2019-02-11T110011.038209.snakemake.log
```
The transcripts and annotations were downloaded from:
https://www.vectorbase.org/downloads?field_organism_taxonomy_tid%5B%5D=372&field_status_value=Current

I used:
Aedes-aegypti-LVP_AGWG_TRANSCRIPTS_AaegL5.1.fa
Aedes-aegypti-LVP_AGWG_BASEFEATURES_AaegL5.1.gff3
Aedes-aegypti-LVP_AGWG_BASEFEATURES_AaegL5.1.gtf

I was running a test with 12 barcoded samples on a couple flow cells so the reads range from 120k to 500k each.

Cheers

**Comment by bsipos** [comment]
Could you please paste in the config file?
Botond

**Comment by cerdelyan** [comment]
```
---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "mosquito"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "Workspaces"
# Results directory:
resdir: "results"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-transcriptome-de"

## Pipeline-specific parameters:

transcriptome: "Aedes-aegypti-LVP_AGWG_TRANSCRIPTS_AaegL5.1.fa"

annotation: "Aedes-aegypti-LVP_AGWG_BASEFEATURES_AaegL5.1.gtf"

control_samples:
    C0h1: "barcode01.fastq"
    C0h2: "barcode02.fastq"
    C0h3: "barcode03.fastq"

treated_samples:
    3h1: "barcode04.fastq"
    3h2: "barcode05.fastq"
    3h3: "barcode06.fastq"
    6h1: "barcode07.fastq"
    6h2: "barcode08.fastq"
    6h3: "barcode09.fastq"
    24h1: "barcode10.fastq"
    24h2: "barcode11.fastq"
    24h3: "barcode12.fastq"

minimap_index_opts: ""

minimap2_opts: ""

maximum_secondary: 100

secondary_score_ratio: 1.0

salmon_libtype: "SF"

# Count filtering options - customize these according to your experimental design:

# Genes expressed in minimum this many samples:
min_samps_gene_expr: 3
# Transcripts expressed in minimum this many samples:
min_samps_feature_expr: 1
# Minimum gene counts:
min_gene_expr: 10
# Minimum transcript counts:
min_feature_expr: 3


threads: 50
```

Cheers

**Comment by bsipos** [comment]
Could you please also paste in the file "de_analysis/coldata.tsv" and the head of "merged/all_counts.tsv"?

**Comment by cerdelyan** [comment]
Hi Botond,

This is de_analysis/coldata.tsv
```
sample condition type
C0h1 untreated single-read
C0h2 untreated single-read
C0h3 untreated single-read
3h1 treated single-read
3h2 treated single-read
3h3 treated single-read
6h1 treated single-read
6h2 treated single-read
6h3 treated single-read
24h1 treated single-read
24h2 treated single-read
24h3 treated single-read
```
This is the header for merged/all_counts.tsv
```
Reference C0h3 3h2 24h2 3h3 24h3 24h1 C0h1 6h3 3h1 6h2 C0h2 6h1
```
Cheers

**Comment by bsipos** [comment]
Hi,

Please have a letter prefix to all your sample names, like:

```
control_samples:
    C0h1: "barcode01.fastq"
    C0h2: "barcode02.fastq"
    C0h3: "barcode03.fastq"

treated_samples:
    s3h1: "barcode04.fastq"
    s3h2: "barcode05.fastq"
    s3h3: "barcode06.fastq"
    s6h1: "barcode07.fastq"
    s6h2: "barcode08.fastq"
    s6h3: "barcode09.fastq"
    s24h1: "barcode10.fastq"
    s24h2: "barcode11.fastq"
    s24h3: "barcode12.fastq"

```
Also, if this is non-directional cDNA data then the salmon_libtype should be "U".

Regards,
Botond
