### ISSUE TITLE
A question about setting of config.yml

### ISSUE THREAD

**Issue by weir12** [nanoporetech/pipeline-transcriptome-de#2]
Hi Botond,

I was in a trouble when I tried to run sankefile like this: 
`$ snakemake --use-conda -j 4  all`
**Error Report**:
```
 Building DAG of jobs...
 MissingInputException in line 23 of /home/weir/software/pipeline-transcriptome-de/Snakefile:
 Missing input files for rule build_minimap_index:
 Araport11_genes.201606.cdna.fasta
```
Attached my config.yml 
```
---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "Nanopore-DES-Analysis"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "/home/weir/output/"
# Results directory:
resdir: "/home/weir/output/Nanopore-DEG-Analysis/result_DEG"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-transcriptome-de"

## Pipeline-specific parameters:

transcriptome: "Araport11_genes.201606.cdna.fasta"
annotation: "Araport11_GFF3_genes_transposons.gtf"

control_samples:
    Col0_1: "col0_1.fastq"
    Col0_2: "col0_2.fastq"
    Col0_3: "col0_3.fastq"

treated_samples:
    fip37_1: "fip37_1.fastq"
    fip37_2: "fip37_2.fastq"
    fip37_3: "fip37_3.fastq"

minimap_index_opts: ""

minimap2_opts: "-ax splice -uf -k14 ref.fa direct-rna.fq"

maximum_secondary: 100

secondary_score_ratio: 1.0

salmon_libtype: "SF"

# Count filtering options - customize these according to your experimental design:

# Genes expressed in minimum this many samples:
min_samps_gene_expr: 3
# Transcripts expressed in minimum this many samples:
min_samps_feature_expr: 1
# Minimum gene counts:
min_gene_expr: 10
# Minimum transcript counts:
min_feature_expr: 3


threads: 8
```
The **transcripts and annotations** were downloaded from:(https://www.arabidopsis.org/)
**minimap2** --version :2.15-r905
**snakemake** was installed  by conda(4.6.7).
All my input files are exist in `/home/weir/output/Nanopore-DEG-Analysis/`
In addition,I successfully tried **manually indexing ref.fa by minimap2** command: **minimap2 -d ref.mmi ref.fa**
